[package]
name = "susi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# add serde_json to your dependencies
serde_json = "1.0.64"
regex = "1.4.3"